config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup-attempt', to: 'users#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :match_players
  resources :fixture_teams
  resources :matches
  resources :fixtures, only: [:index, :show]
  resources :players
  resources :teams
  resources :colleges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
    has_many :teams
    has_one_attached :shield

end

app/models/fixture.rb
class Fixture < ApplicationRecord
    has_many :matches
    has_many :fixture_teams #each fixture has 2 fixture_teams
    has_many :teams, through: :fixture_teams

    def format_date_time
        min = self.date_time.min - self.date_time.min % 15
        # we want the minutes to occur in multiples of 15
        self.date_time.strftime("%A, %B %d, %Y %H:#{min}")
    end

    def self.in_order
        Fixture.all.sort_by{|fixture| fixture.date_time}
    end

    def self.upcoming_fixtures
        Fixture.in_order.select{|fixture| fixture.date_time > Time.now}
    end

    def self.past_fixtures
        Fixture.in_order.select{|fixture| fixture.date_time < Time.now}
    end

    def self.date_times
        date_times = Fixture.in_order.map{|fixture| fixture.date_time}
    end

    def self.dates
        dates = Fixture.date_times.map{|dt| dt.to_date}.uniq
    end

    def self.fixtures_by_date
        fixtures_by_date = {}
        dates = Fixture.dates
        dates.each do |date|
            fixtures_on_current_date = Fixture.in_order.select{|f| f.date_time.to_date == date}
            fixtures_by_date[date] = fixtures_on_current_date
        end

        fixtures_by_date
    end

    def first_team
        self.fixture_teams.first.team
    end

    def second_team
        self.fixture_teams.last.team
    end
end

app/models/fixture_team.rb
class FixtureTeam < ApplicationRecord
    belongs_to :fixture
    belongs_to :team

    def calculate_score
        c = 0
        self.team.matches
    end
end

app/models/match.rb
class Match < ApplicationRecord
    belongs_to :fixture
    has_many :match_players
    has_many :players, through: :match_players
end

app/models/match_player.rb
class MatchPlayer < ApplicationRecord
    belongs_to :match
    belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team
    has_many :match_players
    has_many :matches, through: :match_players
    has_many :fixtures, through: :matches

    def name
        "#{self.first_name} #{self.last_name}"  
    end
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :college
    has_many :players
    has_many :fixture_teams
    has_many :fixtures, through: :fixture_teams

    def num_games_played
        self.fixtures.select{|f| f.completed == true }.count
    end

    def num_games_won
        self.fixture_teams.select{|ft| ft.winner == true}.count
    end

    def num_games_lost
        self.fixture_teams.select{|ft| ft.winner == false}.count
    end


end

app/models/user.rb
class User < ApplicationRecord
    # stretch goal: for a user to have comments
    has_secure_password
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
    before_action :redirect_if_not_signed_in, only: [:show]

    def index
        @fixture_dates = Fixture.dates
        @upcoming_fixture_dates = @fixture_dates.select{|date| date > Time.now}
        @fixtures_by_date = Fixture.fixtures_by_date
    end

    def show
        @fixture = Fixture.find(params[:id])
        @team1 = @fixture.teams[0]
        @team2 = @fixture.teams[1]

    end

    private 




end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :redirect_if_not_signed_in

    def index
        @players = Player.all
    end

    def show
        @player = Player.find(params[:id])
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :redirect_if_not_signed_in

    def index
        @teams = Team.all
    end

    def show
        @team = Team.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to fixtures_path
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :fullname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @user = User.find_by_id(session[:user_id])
    end

    def signed_in?
        !!current_user
    end
end

app/helpers/fixture_teams_helper.rb
module FixtureTeamsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/match_players_helper.rb
module MatchPlayersHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fixtures/index.html.erb
<div class="container">
    <div class="row">
        <h1 class="display-1">Upcoming Fixtures</h1>
    </div>
    
    <% if signed_in? %>
        <h2><%= link_to 'All Teams', teams_path %></h2>

        <h2><%= link_to 'All Players', players_path %></h2>

        <p><%= button_to('Sign Out', signout_path, method: 'delete')%></p>
        <% else %>
            <p><%= button_to('Sign Up/Sign In', signup_path, method: 'get')%></p>
    <% end %>
    <br>
    <% @upcoming_fixture_dates.each do |date| %>
        <div class="row">
            <h3><%=date.strftime("%A, %B %d, %Y")%></h3>
        </div>
        <ul>
            <% @fixtures_by_date[date].each do |fixture| %>

                <div class="row bg-light position-relative">
                    <p class="col-2 mt-4 ml-4 ">
                        <strong> <%= fixture.first_team.name %> </strong> 
                    </p>
                    <p class="col-1 mt-4 ps-md-0">
                        <%= image_tag(fixture.first_team.college.shield, class: "w-25") %>
                    </p>
                    <p class="col-1 mt-4 ps-md-0">
                        <%= fixture.date_time.strftime("%H:%M") %>
                    </p>
                    <p class="col-1 mt-4 ps-md-0">
                        <%= image_tag(fixture.second_team.college.shield, class: "w-25") %>
                    </p>
                    <p class="col-2 mt-4">
                        <strong> <%= fixture.second_team.name %> </strong> 
                    </p>
                    
                    <a href="<%= fixture_path(fixture) %>" class="stretched-link col offset-md-4 p-4 ps-md-0"> 
                        <span aria-hidden="true">&raquo;</span>
                    </a>

                </div>

            <% end %>
        </ul>

    <% end %>
</div>

app/views/fixtures/show.html.erb
<div class="container">
    <h1 class="display-1">Fixture Show Page</h1>
    <br>
    <table class="table table-hover table-borderless">
        <thead>
            <tr>
                <th scope="col"><%= link_to @team1.name, team_path(@team1) %></th>
                <th scope="col">&nbsp;</th>
                <th scope="col"><%= link_to @team2.name, team_path(@team2) %></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><%=  @team1.num_games_played %></th>
                <td>Games Played</td>
                <td><%= @team2.num_games_played %></th>
            </tr>
            <tr>
                <td><%=  @team1.num_games_won %></th>
                <td>Won</td>
                <td><%= @team2.num_games_won %></td>
            </tr>
            <tr>
                <td><%=  @team1.num_games_lost %></th>
                <td>Lost</td>
                <td><%= @team2.num_games_lost %></td>
            </tr>
        </tbody>
    </table>


    <%= link_to "Back to Fixtures", fixtures_path %>
            
</div>